source-file ~/.config/tmux/reset.conf

# Setup statusbar
source-file ~/.config/tmux/status.conf

# Setup key bindings
source-file ~/.config/tmux/bind.conf

# True color support
# set -g default-terminal "xterm-256color"
# set -ga terminal-overrides ",xterm-256color:Tc"

# General settings
set -s escape-time 0            # faster command sequences
set -sg repeat-time 1000        # increase repeat timeout
set -s focus-events on          # enable focus events
set -g mouse on                 # enable mouse support

set -g extended-keys on         # enable extended keys (for better key bindings)
%if "#{>=:#{version},3.5}"
set -g extended-keys-format csi-u
%endif

set -g history-limit 100000     # increase history size (from 2,000)

# Windows
set -g base-index 1           # start windows numbering at 1
set -g renumber-windows on    # renumber windows when a window is closed
set -g automatic-rename on    # rename window to reflect current program
set -g automatic-rename-format "#{b:pane_current_path}" # only show the current program name in the window title

# Panes
setw -g pane-base-index 1     # make pane numbering consistent with windows
set -g pane-border-lines single  # use simple lines for pane borders
set -g pane-border-style 'fg=#3a3a3a'  # set pane border color
set -g pane-active-border-style 'fg=#5f8787,dim'  # set pane border color

# Display
set -g set-titles on          # set terminal title

set -g display-time 1000      # slightly longer status messages display time
set -g display-panes-time 800 # slightly longer pane indicators display time

# Vim-style copy mode
setw -g mode-keys vi
set -g set-clipboard on          # use system clipboard
set -g allow-passthrough on      # allow keys to pass through to applications in copy mode
setw -g mode-style 'fg=#1F1F28,bg=#7E9CD8'

# Notifications
set -g monitor-bell on
set -g bell-action other
setw -g window-status-bell-style 'fg=#ff6c6b,bg=#1f1f28,bright'  # style for windows with activity

# Other
set -g visual-bell off
set -g visual-silence off
set -g visual-activity off
set -g monitor-activity off


set -g detach-on-destroy off     # don't detach when the last window is closed


# Plugins
source-file ~/.config/tmux/plugins.conf
