# $HOME/.bashrc for bash-3.0 (or later)
# By Kirill Klenov horneds@gmail.com
# ======================================
# vim:ft=sh:fdm=marker


# if not running interactively, don't do anything
[ -z "$PS1" ] && return

__command () {
    command -v $1 1>/dev/null
}

setup () {

    local SRCDIR=$HOME/.home
    local CFGDIR=$SRCDIR/cfg
    local LIBDIR=$SRCDIR/lib

    local INCDIR=$CFGDIR/bash/include
    local CMPDIR=$CFGDIR/bash/completion
    local OS_VERSION=$(uname -s)
    
    # Load options
    source $INCDIR/options.sh

    # Load colors
    source $INCDIR/colors.sh

    # Load path
    source $INCDIR/path.sh

    # Load functions
    source $INCDIR/functions.sh

    # Setup PS
    source $INCDIR/ps.sh

    # Setup gpg
    source $INCDIR/gpg.sh

    # Setup completion
    source /usr/local/etc/bash_completion 2>/dev/null || source /etc/bash_completion 2> /dev/null
    source $CMPDIR/makesite.sh
    source $CMPDIR/cd_.sh
    source $CMPDIR/rmqadmin.sh

    # Setup tools
    source $INCDIR/ruby.sh
    source $INCDIR/python.sh
    source $INCDIR/git.sh

    # Close promt
    PS1="${PS1}\n$ "

    # Smartcd
    [ -d $LIBDIR/smartcd/lib ] && {

        source $LIBDIR/smartcd/lib/core/arrays
        source $LIBDIR/smartcd/lib/core/varstash
        source $LIBDIR/smartcd/lib/core/smartcd
        smartcd setup cd
        smartcd setup pushd
        smartcd setup popd
        smartcd setup completion
    
    }

    # Load aliases
    source ~/.bash_aliases 2>/dev/null

    # Load local settings
    source ~/.bash_local 2>/dev/null

    # Show login screen
    source $INCDIR/login.sh

    # Auto run screen on remote servers
    __command screen && {
        if [ ! -z "$SSH_CLIENT" ] && [ -z $WINDOW ]; then
            exec screen
        fi
    }

    if [ "$TERM" != "dumb" ]; then
        export LS_OPTIONS='--color=auto --group-directories-first'
        eval `dircolors $CFGDIR/dir_colors`
    fi
}

setup && unset setup

# Changing the terminal title to the last shell command
trap 'echo -e "\e]0;$BASH_COMMAND\007"' DEBUG
