.PHONY: install uninstall
install:
	npm install -g @mariozechner/pi-coding-agent
	# pi install npm:@haispeed/pi-deck

uninstall:
	npm uninstall -g @mariozechner/pi-coding-agent @haispeed/pi-deck || true
