#!/bin/bash

# $HOME/.bashrc for bash-3.0 (or later)
# By Kirill Klenov horneds@gmail.com
# ======================================
# vim:ft=sh:fdm=marker

# Skip remaining setup if not an interactive shell
[[ $- != *i* ]] && return

# Load env
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
source $XDG_CONFIG_HOME/bash/env.sh

# Setup path
source $XDG_CONFIG_HOME/bash/path.sh

# Load options
source $XDG_CONFIG_HOME/bash/options.sh

# Load colors
source $XDG_CONFIG_HOME/bash/colors.sh

# Load functions
source $XDG_CONFIG_HOME/bash/functions.sh

# Setup gpg (disabled now)
# source $XDG_CONFIG_HOME/bash/include/gpg.sh

# Setup PS
source $XDG_CONFIG_HOME/bash/ps.sh

# Setup completions
source /etc/bash_completion 2>/dev/null || source $XDG_CONFIG_HOME/bash/include/bash-completion

# Setup tools
source $XDG_CONFIG_HOME/bash/include/android.sh
source $XDG_CONFIG_HOME/bash/include/conda.sh
source $XDG_CONFIG_HOME/bash/include/docker.sh
source $XDG_CONFIG_HOME/bash/include/dotfiles.sh
source $XDG_CONFIG_HOME/bash/include/git.sh
source $XDG_CONFIG_HOME/bash/include/homebrew.sh
source $XDG_CONFIG_HOME/bash/include/llm.sh
source $XDG_CONFIG_HOME/bash/include/lua.sh
source $XDG_CONFIG_HOME/bash/include/node.sh
source $XDG_CONFIG_HOME/bash/include/pass.sh
source $XDG_CONFIG_HOME/bash/include/python.sh
source $XDG_CONFIG_HOME/bash/include/tmux.sh
source $XDG_CONFIG_HOME/bash/include/yandex.sh
hash go 2>/dev/null && source $XDG_CONFIG_HOME/bash/include/go.sh
hash rustc 2>/dev/null && source $XDG_CONFIG_HOME/bash/include/rust.sh
hash ruby 2>/dev/null && source $XDG_CONFIG_HOME/bash/include/ruby.sh
hash uv 2>/dev/null && source $XDG_CONFIG_HOME/bash/include/uv.sh

# Aliases
source $XDG_CONFIG_HOME/bash/aliases.sh

# Show login screen
source $XDG_CONFIG_HOME/bash/login.sh

# Close promt
PS1="${PS1}\n$ "

# Smartcd
source $XDG_CONFIG_HOME/bash/smartcd.sh

# Auto run screen on remote servers
hash screen 2>/dev/null && {
  if [ ! -z "$SSH_CLIENT" ] && [ -z $WINDOW ]; then
    exec screen
  fi
}

# Changing the terminal title to the last shell command
# trap 'echo -e "\e]0;$BASH_COMMAND\007"' DEBUG

# Load local settings
source $HOME/.bash_local 2>/dev/null
