---
- hosts: all
  tasks:
    - community.general.homebrew_cask: name={{item}}
      with_items:
        - alfred            # UI
        - appcleaner        # Clean applications
        - calibre           # Books Manager
        - docker            # Utilities
        - google-chrome     # Browser
        - google-drive      # Cloud storage
        - iina              # Video player
        - ilya-birman-typography-layout # Keyboard layout
        - istat-menus       # Activity Monitor
        - iterm2            # Terminal
        - karabiner-elements # Keyboard
        - keepingyouawake   # Keep Mac awake
        - lulu              # Firewall
        - obsidian          # Knowledge base
        - rectangle         # Window manager
        - slack             # Messenger
        - steam             # Games Store and Manager
        - telegram          # Messenger
        - the-unarchiver    # Archive manager
        - transmission      # Lightweight Bittorrent client
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - community.general.homebrew_tap:
        name: homebrew/cask-fonts

    - community.general.homebrew_cask:
        name: font-hack-nerd-font
