---

- hosts: all
  tasks:
  # - homebrew: name=caskroom/cask/brew-cask
  - homebrew_cask: name={{item}}
    with_items:
    - alfred            # UI
    - blockblock
    - calibre
    - ccleaner
    - dash
    - docker
    - firefox
    - gimp
    - google-chrome     # Browser
    - hyperdock         # Manage windows
    - iina              # Video player
    - ilya-birman-typography-layout
    - istat-menus       # Monitor
    - iterm2            # Terminal
    - lulu              # Firewall
    - obs
    - obs-virtualcam
    - parallels15       # Virtualization
    - postman           # Development
    - slack             # Messenger
    - spotify           # Media
    - steam             # Games
    - telegram          # Messenger
    - the-unarchiver    # Archive manager
    - transmission      # Torrent Client
    - tunnelblick       # VPN manager
    - zoomus            # Messenger
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
