---
- hosts: all
  tasks:
    - community.general.homebrew_cask: name={{item}}
      with_items:
        - alfred            # UI
        - calibre           # Books Manager
        # - ccleaner          # System cleaner
        - dash              # Documentation searcher
        - docker            # Utilities
        # - firefox           # Browser
        - google-chrome     # Browser
        - google-drive      # Cloud storage
        - hyperdock         # Manage windows
        - iina              # Video player
        - ilya-birman-typography-layout # Keyboard
        - istat-menus       # Activity Monitor
        - iterm2            # Terminal
        - karabiner-elements # Keyboard
        - keepingyouawake   # Keep Mac awake
        # - kitty             # Terminal
        - lulu              # Firewall
        # - obs               # Video Streams
        # - obs-virtualcam
        # - parallels         # Virtualization
        - slack             # Messenger
        # - spotify # Media
        - steam # Games
        - telegram # Messenger
        - the-unarchiver # Archive manager
        - qbittorrent         # Torrent Client
        # - transmission # Torrent Client
        # - tunnelblick # VPN manager
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - community.general.homebrew_tap:
        name: homebrew/cask-fonts

    - community.general.homebrew_cask:
        name: font-hack-nerd-font 
