---

- homebrew: update_homebrew=yes

- name: Install setup utils
  homebrew:
    name:
    - cowsay
    - fortune
    - stow

- name: Install terminal utils
  homebrew:
    name:
    - bash              # shell
    - bash-completion   # shell-completion
    - bat               # replacement for cat
    - coreutils
    - pass
    - ripgrep
    - terminal-notifier
    - zoxide            # replacement for cd

- name: Install editors
  homebrew:
    name:
    - vim
    - neovim

- name: Install languages / packages
  homebrew:
    name:
    - golang
    - luarocks  # Lua package/versions manager
    - nvm       # Node versions manager
    - pyenv     # Python versions manager
    - rust
    - yarn

- name: Install other tools
  homebrew:
    name:
    - ctags
    - fzf
    - git-flow
    - htop-osx
    - httpie
    - mplayer
    - mpv
    - rsc_2fa
    - stylua
    - unzip
    - wget

- name: Python packages
  ansible.builtin.pip:
    name:
    - wheel
    - setuptools
    - requests
    - dnspython
    - psutil
