---

- hosts: all

  vars_files:
    - vars.yml

  tasks:

    - name: RedHat
      ansible.builtin.import_tasks: install/RedHat.yml
      when: ansible_facts['os_family'] == "RedHat"
      become: true

    - name: Debian
      ansible.builtin.import_tasks: install/Debian.yml
      when: ansible_facts['os_family'] == "Debian"
      become: true

    - name: Darwin
      ansible.builtin.import_tasks: install/Darwin.yml
      when: ansible_facts['os_family'] == "Darwin"

    - name: Setup ssh - pt. 1
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.ssh"
        state: directory
        owner: "{{ home_user }}"
        mode: "0700"

    - name: Setup ssh - pt. 2
      ansible.builtin.lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.ssh/authorized_keys"
        line: "{{ item }}"
        create: true
        owner: "{{ home_user }}"
        mode: "0600"
      loop: "{{ home_authorized_keys }}"

    - name: Setup ssh - pt. 3
      ansible.builtin.lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.ssh/known_hosts"
        line: "{{ item }}"
        create: true
        owner: "{{ home_user }}"
        mode: "0644"
      loop: "{{ home_fingerprints }}"
