---

- hosts: all

  vars_files:
    - vars.yml

  tasks:

    - name: RedHat
      import_tasks: install.yum.yml
      when: ansible_os_family == "RedHat"
      become: true

    - name: Debian
      import_tasks: install.deb.yml
      when: ansible_os_family == "Debian"
      become: true

    - name: Darwin
      import_tasks: install.mac.yml
      when: ansible_os_family == "Darwin"

    - name: Setup ssh - pt. 1
      ansible.builtin.file:
        path: "/home/{{ home_user }}/.ssh"
        state: directory
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0700"

    - name: Setup ssh - pt. 2
      ansible.builtin.lineinfile:
        path: "/home/{{ home_user }}/.ssh/authorized_keys"
        line: "{{ item }}"
        create: true
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0600"
      loop: "{{ home_authorized_keys }}"

    - name: Setup ssh - pt. 3
      ansible.builtin.lineinfile:
        path: "/home/{{ home_user }}/.ssh/known_hosts"
        line: "{{ item }}"
        create: true
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0644"
      loop: "{{ home_fingerprints }}"
