---

- hosts: all

  vars_files:
  - vars.yml

  tasks:

  - import_tasks: install.yum.yml
    when: ansible_os_family == "RedHat"
    become: yes

  - import_tasks: install.deb.yml
    when: ansible_os_family == "Debian"
    become: yes

  - import_tasks: install.mac.yml
    when: ansible_os_family == "Darwin"

  - name: Setup ssh - pt. 1
    file: state=directory dest=~{{home_user}}/.ssh owner={{home_user}}

  - name: Setup ssh - pt. 2
    lineinfile: >
      dest=~{{home_user}}/.ssh/authorized_keys
      line="{{item}}"
      create=yes
    with_items: "{{home_authorized_keys}}"

  - name: Setup ssh - pt. 3
    lineinfile: >
      dest=~{{home_user}}/.ssh/known_hosts
      line="{{item}}"
      create=yes
    with_items: "{{home_fingerprints}}"

# vim:sw=2:ft=ansible
