---
- hosts: all

  vars_files:
    - vars.yml

  handlers:
    - name: Restart Dock
      ansible.builtin.command: killall Dock
      changed_when: false
      failed_when: false

  tasks:
    - name: Configure macOS sleep and power settings
      ansible.builtin.command: pmset -a {{ item.key }} {{ item.value }}
      become: true
      changed_when: false
      loop:
        - { key: sleep, value: 0 }
        - { key: displaysleep, value: 0 }
        - { key: disksleep, value: 0 }
        - { key: standby, value: 0 }
        - { key: powernap, value: 0 }

    - name: Disable automatic window animations
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticWindowAnimationsEnabled
        value: false
        type: bool
        state: present

    - name: Disable App Nap
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAppSleepDisabled
        value: true
        type: bool
        state: present

    - name: Disable Dock launch animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: launchanim
        value: false
        type: bool
        state: present
      notify: Restart Dock

    - name: Disable Spotlight indexing
      ansible.builtin.command: mdutil -a -i off
      become: true
      changed_when: false

    - name: Erase Spotlight index
      ansible.builtin.command: mdutil -E /
      become: true
      changed_when: false

    - name: Disable Time Machine
      ansible.builtin.command: tmutil disable
      become: true
      changed_when: false

    - name: Disable photoanalysisd launch agent
      ansible.builtin.command: launchctl disable gui/{{ ansible_facts['user_uid'] }}/com.apple.photoanalysisd
      changed_when: false
      failed_when: false

    - name: Increase launchctl maxfiles limits
      ansible.builtin.command: launchctl limit maxfiles 65536 200000
      become: true
      changed_when: false
