#!/bin/bash

# $HOME/.bashrc for bash-3.0 (or later)
# By Kirill Klenov horneds@gmail.com
# ======================================
# vim:ft=sh:fdm=marker

# Skip remaining setup if not an interactive shell
[[ $- != *i* ]] && return

# Load env
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
source $XDG_CONFIG_HOME/bash/env.sh

# Setup path
source $XDG_CONFIG_HOME/bash/path.sh

# Load options
source $XDG_CONFIG_HOME/bash/options.sh

# Load colors
source $XDG_CONFIG_HOME/bash/colors.sh

# Load functions
source $XDG_CONFIG_HOME/bash/functions.sh

# Setup gpg (disabled now)
# source $XDG_CONFIG_HOME/bash/include/gpg.sh

# Setup PS
source $XDG_CONFIG_HOME/bash/ps.sh

# Setup completions
source /etc/bash_completion 2>/dev/null || source $XDG_CONFIG_HOME/bash/include/bash-completion

# Setup tools and apps
source $XDG_CONFIG_HOME/bash/include/index.sh

# Aliases
source $XDG_CONFIG_HOME/bash/aliases.sh

# Show login screen
source $XDG_CONFIG_HOME/bash/login.sh

# Close prompt
PS1="${PS1}\n$ "

# Smartcd
source $XDG_CONFIG_HOME/bash/smartcd.sh

# Changing the terminal title to the last shell command
# trap 'echo -e "\e]0;$BASH_COMMAND\007"' DEBUG

# Load local settings
source $HOME/.bash_local 2>/dev/null
